In [7]:
def share_bread(n, k):
    n = n
    k = k
    x = k//n
    y = k % n
    return x, y


assert share_bread(n=3, k=14) == (4, 2)


In [13]:
def leap_year(year):
    if (year%4==0 and year%100 != 0) or year%400==0:
        text_result = 'YOU SHALL PASS'
    else:
        text_result = 'YOU SHALL NOT PASS'
    return text_result


assert leap_year(5) == 'YOU SHALL NOT PASS'


In [8]:
def amulet_area(a, b, c):
    p = (a+b+c)/2
    s = (p*(p - a)*(p - b)*(p - c))**0.5
    return s


assert amulet_area(3, 4, 5) == 6


In [9]:
import numpy as np


def cal_euclidean(a, b):
    d = np.sum(np.square(a, b))
    distance = np.sqrt(d)
    return distance


def cal_manhattan(a, b):
    distance = np.linalg.norm(a-b, ord=1)
    return distance


def cal_cosine(a, b):
    distance = np.dot(a, b) / (np.linalg.norm(a) * np.linalg.norm(b))
    return distance


a = np.random.randint(-10, 10, size=10)
b = np.random.randint(-10, 10, size=10)
print(cal_euclidean(a, b))
print(cal_manhattan(a, b))
print(cal_cosine(a, b))

14.933184523068078
236.0
-0.507333271492194


In [10]:
import numpy as np

my_array = np.random.randint(0, 2, size=100)
print(np.max(my_array), np.min(my_array))
print(my_array)

my_array = np.random.randint(0, 50, (5, 6))
selected_column = my_array.max()
print('Shape: ', my_array.shape)
print('Array')
print(my_array)
print(selected_column)


def get_unique_rows(x):
    x_unique = np.unique(x, axis=0)
    return x_unique


x = np.random.randint(4, 6, size=(10, 3))
print(x)
get_unique_rows(x)


1 0
[0 1 0 0 1 1 1 1 1 1 0 0 1 1 0 1 1 1 0 1 1 1 0 0 1 0 0 1 1 1 1 0 0 1 0 1 1
 1 1 1 1 1 1 1 1 1 0 0 0 1 0 1 0 1 0 0 1 0 0 1 1 0 1 1 0 0 1 1 1 0 0 1 1 1
 1 1 0 1 0 0 0 0 0 0 0 1 0 1 1 0 0 0 0 0 0 0 0 0 0 0]
Shape:  (5, 6)
Array
[[ 3 26  2 37  3 47]
 [28 24 14 38 32 23]
 [ 0 15 21  3 40  3]
 [47 40 45 47 36 48]
 [34  7 23 14 46 14]]
48
[[5 4 5]
 [5 4 4]
 [5 5 5]
 [5 4 4]
 [4 5 4]
 [5 4 4]
 [5 4 4]
 [5 5 4]
 [5 4 5]
 [4 4 4]]


array([[4, 4, 4],
       [4, 5, 4],
       [5, 4, 4],
       [5, 4, 5],
       [5, 5, 4],
       [5, 5, 5]])